version: '3.7'

services:
  frontend:
    build: frontend
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    command: npm run start

  backend:
    build: backend
    container_name: backend

    ports:
      - "4000:4000"

    command: npm run start
    